### ISSUE TITLE
Turning Motor Encoders

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#1]
As in the example below we need to use the absolute encoders for the turning motors on each swerve module.  Currently, it looks like we are using the internal encoder for the motor which will be be a relative position depending on where the rotor is when the controller starts.  To use the attached absolute encoder we need to replace the getEncoder() calls with getAbsoluteEncoder().  

Example swerve drive using SparkMax  CANBus and attached absolute encoder:  
https://github.com/REVrobotics/MAXSwerve-Java-Template/blob/main/src/main/java/frc/robot/subsystems/MAXSwerveModule.java

**Comment by jwr1** [comment]
Complete in b0fac65dfb2a0303cd468d63e2ec7f698efcdc5e
