### ISSUE TITLE
Add the NavX in place of the analog gyro

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#2]
The example code we started with used an analog gyro.  We have a NavX board to use like we did last year : https://github.com/Team5830/2023-Charged-Up/blob/main/src/main/java/frc/robot/subsystems/DriveTrain.java

For the moment we should stick with the USB interface, but if we have time we might try to switch to the SPI interface later (especially if we need the USB for something else). (https://pdocs.kauailabs.com/navx-mxp/guidance/selecting-an-interface/)

**Comment by jwr1** [comment]
Complete with c297b1d11ba53cea03c3bb44b2825c5d691a0c6f
