### ISSUE TITLE
Move numbers into constants file

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#4]
Move numbers or values that are in code and might need to be changed into Constants.java.  This is helpful as we adjust parameters so that we don't have to hunt around for the "magic" numbers in code when we want to change something.  So the random numbers we see in code such as PID parameters, CAN bus ID's should be moved into the constants and given a helpful, descriptive name .

**Comment by jwr1** [comment]
Complete in 455f90f3fad87fdcc2cb08266b04a26b24b62c7d
