### ISSUE TITLE
Swerve Module Drive Motor Encoder and controller defaults

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#5]
The SwerveModule subsystem needs to set a conversion factor for the drive motor encoders.  Probably it would also be good to start the motor controllers fresh with the factory default so that our code is completely setting the configuration. 

Previously we used:
leftLeadMotorController = new CANSparkMax(ValueConstants.kLeftMotor1Port, CANSparkMax.MotorType.kBrushless);
leftLeadMotorController.restoreFactoryDefaults();
leftLeadEncoder = leftLeadMotorController.getEncoder();
leftLeadEncoder.setPositionConversionFactor(18.84 * 2.54 / 8.33 / 100);
 
https://github.com/Team5830/2023-Charged-Up/blob/main/src/main/java/frc/robot/subsystems/DriveTrain.java

The conversion factor above was to get the distance the wheels traveled in meters:
The drive wheel circumference in inches (previously 18.84, will need to measure it on the new wheels)
X 2.54 (centimeters/Inches)  
/ Drive Gear Ratio  (was 8.33, should be 6.55 with our swerve drive)  
/ 100 (meters/centimeters)

**Comment by jwr1** [comment]
Fixed in eb3dcc9d491e55b7facd8d16047835c918f5de15 and 7cadc2f4fe1b6b319f883cd9fc24cfa08d8f150d
