### ISSUE TITLE
Add try catches for all hardware instantiations

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#6]
In order to keep the code running when a hardware device is not reachable we should wrap the instantiation in a try catch so if it fails the code will report the error and continue.  It looks like we need this in all the subsystems talking to motors including the swerve drive modules.  For the swerve drive we could either include it in the SwerveModule or in the SwerveDrive when the modules are initialized.

Example: https://github.com/Team5830/2023-Charged-Up/blob/main/src/main/java/frc/robot/subsystems/Arm.java

**Comment by jwr1** [comment]
Fixed in 852a9c9dd94d6991bd24831da8cc3e837a4eb5e6
