### ISSUE TITLE
Create Arm subsystem

### ISSUE THREAD

**Issue by asteele11** [Team5830/2024-Crescendo#8]
We should have a single motor driven arm.  This will need to have limits set so the arm returns to the correct position and doesn't extend too far.  Not sure what those exact values will be yet but would be good to put them in as values in the constants.  
There will also likely be set positions for the arm with adjustments.  Should be positions for pickup, shoot and the amplifier.   

Example:
https://github.com/Team5830/2023-Charged-Up/blob/main/src/main/java/frc/robot/subsystems/Arm.java

**Comment by jwr1** [comment]
Complete in 4791df631a39404b8e9b3151780ff9273160e740
